package promptflow

// Phase C subjects: Group, Product, Food, Vehicle, Architecture, Character and
// Logo. Each branches on its own `elements~=X` condition and offers Myanmar-
// first suggestion pills. Orders sit above the shared tail so each subject's
// description leads before the camera/style/quality layer is appended.

// --- GROUP (3+ people) -----------------------------------------------------

func groupNodes() []Node {
	const c = "elements~=group"
	return []Node{
		textNode("group_size", 660, false, c,
			"လူဦးရေ မည်မျှ ပါဝင်သလဲ?", "How many people?",
			"{value}",
			o("three", "၃ ယောက်", "3 people", "three people"),
			o("four", "၄ ယောက်", "4 people", "four people"),
			o("five", "၅ ယောက်", "5 people", "five people"),
			o("small", "လူအုပ်စုငယ် (အနည်းငယ်)", "Small group", "a small group of people"),
			o("family4", "မိသားစု (၄ ယောက်)", "Family of four", "a family of four"),
			o("crowd", "လူအုပ်ကြီး", "Large crowd", "a large crowd"),
		),
		textNode("group_who", 662, false, c,
			"မည်သူများ ပါဝင်သလဲ?", "Who are they?",
			"of {value}",
			o("family", "မိသားစုဝင်များ", "Family", "a family"),
			o("friends", "သူငယ်ချင်းများ", "Friends", "friends"),
			o("coworkers", "လုပ်ဖော်ကိုင်ဖက်များ", "Coworkers", "coworkers"),
			o("students", "ကျောင်းသား/သူများ", "Students", "students"),
			o("monks", "သံဃာတော်များ", "Monks", "monks"),
			o("dancers", "ရိုးရာ အကပညာရှင်များ", "Dancers", "traditional dancers"),
			o("band", "တေးဂီတအဖွဲ့", "Band", "a music band"),
			o("team", "အားကစားအသင်း", "Sports team", "a sports team"),
			o("elders", "သက်ကြီးဘိုးဘွားများ", "Elders", "village elders"),
			o("children", "ကလေးငယ်များ", "Children", "children"),
		),
		textNode("group_attire", 664, true, c,
			"မည်သို့သော ဝတ်စုံ ဝတ်ဆင်ထားသလဲ?", "Attire?",
			"wearing {value}",
			o("traditional", "မြန်မာ့ရိုးရာ ဝတ်စုံ", "Traditional dress", "traditional Myanmar dress"),
			o("uniform", "တူညီဝတ်စုံ", "Matching uniforms", "matching uniforms"),
			o("casual", "သာမန် ပေါ့ပေါ့ပါးပါး ဝတ်စုံ", "Casual", "casual clothes"),
			o("formal", "အခမ်းအနား ဝတ်စုံ (Formal)", "Formal", "formal wear"),
			o("festival", "ရောင်စုံ ပွဲတော်ဝတ်စုံ", "Festival wear", "colorful festival attire"),
			o("ethnic_mix", "တိုင်းရင်းသားရိုးရာ ဝတ်စုံစုံလင်စွာ", "Mixed ethnic dress", "a mix of ethnic costumes"),
		),
		textNode("group_arrangement", 666, false, c,
			"လူများ နေရာယူထားပုံ အနေအထား?", "Arrangement?",
			"{value}",
			o("row", "တစ်တန်းတည်း တန်းစီရပ်နေသော", "In a row", "standing in a row"),
			o("groupphoto", "အုပ်စုလိုက် ဓာတ်ပုံအရိုက်ခံနေသော", "Group photo", "posing for a group photo"),
			o("around", "ဝိုင်းဖွဲ့ ထိုင်နေသော", "Gathered around", "gathered around a table"),
			o("circle", "အဝိုင်းပုံစံ စုဝေးနေသော", "In a circle", "arranged in a circle"),
			o("candid", "သဘာဝကျကျ အမူအရာဖြင့်", "Candid", "in a candid, natural moment"),
			o("stage", "စင်မြင့်ပေါ်တွင် ရှိနေသော", "On stage", "on a stage"),
		),
		textNode("group_activity", 668, true, c,
			"ဘာလုပ်ဆောင်နေကြသလဲ?", "What are they doing?",
			"{value}",
			o("celebrating", "ပျော်ရွှင်စွာ ပွဲကျင်းပနေသော", "Celebrating", "celebrating together"),
			o("posing", "ကင်မရာရှေ့ ပို့စ်ပေးနေသော", "Posing", "posing for the camera"),
			o("eating", "အတူတကွ လက်ဆုံစားသောက်နေသော", "Eating together", "sharing a meal"),
			o("working", "အတူတကွ အလုပ်လုပ်နေသော", "Working", "working together"),
			o("festival", "ပွဲတော်တွင် ပျော်ပါးနေသော", "At a festival", "at a festival"),
			o("praying", "အတူတကွ ဘုရားရှိခိုး ဆုတောင်းနေသော", "Praying", "praying together"),
			o("dancing", "ကခုန်ပျော်မြူးနေသော", "Dancing", "dancing"),
		),
	}
}

// --- PRODUCT (commercial / e-commerce) -------------------------------------

func productNodes() []Node {
	const c = "elements~=product"
	return []Node{
		textNode("product_what", 700, false, c,
			"မည်သည့် ထုတ်ကုန်ပစ္စည်း အမျိုးအစားလဲ?", "What product is it?",
			"{value}",
			o("cosmetic", "အလှကုန် ပုလင်း", "Cosmetic bottle", "a cosmetic bottle"),
			o("skincare", "အသားအရေထိန်း ခရင်မ်ဗူး", "Skincare jar", "a skincare jar"),
			o("perfume", "ရေမွှေး ပုလင်း", "Perfume bottle", "a perfume bottle"),
			o("coffee_bag", "ကော်ဖီ အိတ်/ထုပ်", "Coffee bag", "a coffee bag"),
			o("beverage", "အချိုရည် သံဗူး", "Beverage can", "a beverage can"),
			o("snack", "မုန့်ထုပ်", "Snack pack", "a snack package"),
			o("watch", "လက်ပတ်နာရီ", "Watch", "a wristwatch"),
			o("phone", "စမတ်ဖုန်း", "Smartphone", "a smartphone"),
			o("headphones", "နားကြပ်", "Headphones", "a pair of headphones"),
			o("sneaker", "စနီကာ / အားကစားဖိနပ်", "Sneaker", "a sneaker"),
			o("handbag", "လက်ဆွဲအိတ်", "Handbag", "a handbag"),
			o("jewelry", "လက်ဝတ်ရတနာ", "Jewelry", "a piece of jewelry"),
			o("candle", "ရနံ့မွှေး ဖယောင်းတိုင်", "Candle", "a scented candle"),
			o("supplement", "အားဆေး / ဖြည့်စွက်စာဗူး", "Supplement jar", "a supplement jar"),
		),
		textNode("product_material", 702, true, c,
			"ပစ္စည်း ကုန်ကြမ်းနှင့် အပြင်မျက်နှာပြင်?", "Material / finish?",
			"made of {value}",
			o("glass", "ကြည်လင်သော ဖန်သား", "Glass", "clear glass"),
			o("frosted", "နှင်းဖုံးဖန်မှိန် (Frosted glass)", "Frosted glass", "frosted glass"),
			o("matte", "အရောင်မပြောင်သော ပလတ်စတစ် (Matte)", "Matte plastic", "matte plastic"),
			o("aluminum", "အလူမီနီယမ် သတ္တု", "Aluminum", "brushed aluminum"),
			o("kraft", "သဘာဝ စက္ကူကြမ်း (Kraft paper)", "Kraft paper", "kraft paper"),
			o("ceramic", "ကြွေထည်", "Ceramic", "ceramic"),
			o("leather", "သားရေထည်", "Leather", "leather"),
			o("gold", "ရွှေရောင် / ရွှေသား", "Gold", "gold"),
		),
		textNode("product_surface", 704, false, c,
			"ပစ္စည်းကို မည်သည့်နေရာတွင် တင်ထားသလဲ?", "Placed on?",
			"{value}",
			o("marble", "စကျင်ကျောက်ပြားပေါ်", "On marble", "on a marble surface"),
			o("wood", "သစ်သားမျက်နှာပြင်ပေါ်", "On wood", "on a wooden surface"),
			o("podium", "စင်မြင့်ခုံငယ် (Podium) ပေါ်", "On a podium", "on a display podium"),
			o("floating", "လေထဲတွင် လွင့်မျောနေဟန်", "Floating", "floating in the air"),
			o("silk", "ပိုးထည်စပေါ်", "On silk", "on silk fabric"),
			o("water", "ရေစင်ရေစက်များဖြင့်", "With water splash", "with water splashes"),
			o("ingredients", "သဘာဝ ပါဝင်ပစ္စည်းများ ဝန်းရံလျက်", "With ingredients", "surrounded by its ingredients"),
			o("stone", "ကျောက်တုံးမျက်နှာပြင်ပေါ်", "On stone", "on a natural stone slab"),
		),
		textNode("product_background", 706, false, c,
			"နောက်ခံ အခင်းအကျင်း?", "Background?",
			"on {value}",
			o("white", "အဖြူရောင် သန့်သန့်", "Clean white", "a clean white background"),
			o("pastel", "နုညံ့သော အရောင် (Pastel)", "Pastel", "a soft pastel background"),
			o("studio", "စတူဒီယို နောက်ခံ", "Studio", "a seamless studio background"),
			o("dark", "အမှောင်ရိပ်ဆန်သော နောက်ခံ", "Dark", "a dark moody background"),
			o("nature", "သဘာဝ ပတ်ဝန်းကျင် နောက်ခံ", "Natural", "a natural outdoor background"),
			o("color_pop", "တောက်ပထင်ရှားသော အရောင်တစ်ပြေးညီ", "Bold color", "a bold solid-color background"),
		),
		textNode("product_shot", 708, true, c,
			"ရိုက်ကွက် ထောင့်နှင့် အမျိုးအစား?", "Shot type?",
			"{value}",
			o("hero", "ပစ္စည်းကို အဓိကပေါ်လွင်စေသော ရိုက်ချက် (Hero shot)", "Hero shot", "a hero product shot"),
			o("closeup", "အနီးကပ် ရိုက်ချက် (Close-up)", "Close-up", "a close-up shot"),
			o("angle45", "၄၅ ဒီဂရီ အစောင်းရိုက်ချက်", "45-degree", "shot at a 45-degree angle"),
			o("flatlay", "အပေါ်တည့်တည့်မှ အပြားရိုက်ချက် (Flat lay)", "Flat lay", "a top-down flat lay"),
			o("macro", "အသေးစိတ် အနီးကပ်ဆုံး ရိုက်ချက် (Macro)", "Macro detail", "an extreme macro detail shot"),
			o("floating_shot", "လွင့်မျောနေသော ရိုက်ချက်", "Floating", "a floating product shot"),
		),
	}
}

// --- FOOD ------------------------------------------------------------------

func foodNodes() []Node {
	const c = "elements~=food"
	return []Node{
		textNode("food_what", 720, false, c,
			"မည်သည့် အစားအသောက် အမျိုးအစားလဲ?", "What food is it?",
			"{value}",
			o("mohinga", "မုန့်ဟင်းခါး", "Mohinga", "a bowl of mohinga"),
			o("laphet", "လက်ဖက်သုပ်", "Tea leaf salad", "a plate of tea leaf salad"),
			o("curry", "မြန်မာထမင်းနှင့် ဟင်းလျာများ", "Rice & curry", "a Burmese rice and curry spread"),
			o("noodles", "ခေါက်ဆွဲ", "Noodles", "a bowl of noodles"),
			o("friedrice", "ထမင်းကြော်", "Fried rice", "a plate of fried rice"),
			o("shannoodle", "ရှမ်းခေါက်ဆွဲ", "Shan noodles", "Shan noodles"),
			o("skewers", "အကင်စုံ", "Grilled skewers", "grilled skewers"),
			o("burger", "ဘာဂါ (Burger)", "Burger", "a burger"),
			o("sushi", "ဆူရှီ (Sushi)", "Sushi", "a sushi platter"),
			o("cake", "ကိတ်မုန့်", "Cake", "a slice of cake"),
			o("coffee", "ကော်ဖီ", "Coffee", "a cup of coffee"),
			o("icecream", "ရေခဲမုန့်", "Ice cream", "a scoop of ice cream"),
			o("fruit", "လတ်ဆတ်သော သစ်သီးစုံ", "Fruit platter", "a fresh fruit platter"),
			o("dessert", "အချိုပွဲ", "Dessert", "a plated dessert"),
		),
		textNode("food_style", 722, false, c,
			"ဟင်းပွဲ ပြင်ဆင်တင်ဆက်ပုံ?", "Plating / style?",
			"{value}",
			o("street", "လမ်းဘေး အစားအစာပုံစံ", "Street food", "in a street-food style"),
			o("finedining", "အဆင့်မြင့် စားသောက်ဆိုင်စတိုင် (Fine dining)", "Fine dining", "with elegant fine-dining plating"),
			o("homestyle", "အိမ်ချက်ဟင်း လက်ရာပုံစံ", "Home-style", "in a rustic home-style"),
			o("banana_leaf", "ငှက်ပျောရွက်ပေါ်တွင် ပြင်ဆင်ထားသော", "On banana leaf", "served on a banana leaf"),
			o("claypot", "မြေအိုးထဲတွင် ထည့်ထားသော", "In a clay pot", "served in a clay pot"),
			o("board", "သစ်သားလင်ပန်း/ခုံပေါ်တွင် တင်ထားသော", "On a board", "on a wooden serving board"),
		),
		textNode("food_detail", 724, true, c,
			"အစားအစာ၏ အသေးစိတ် အသွင်အပြင်?", "Detail?",
			"{value}",
			o("steam", "အငွေ့တထောင်းထောင်း ထွက်နေသော", "Steaming", "with steam rising"),
			o("herbs", "လတ်ဆတ်သော အသီးအရွက်များ ဖြူးထားသော", "Garnished", "garnished with fresh herbs"),
			o("sauce", "ဆော့စ်/အနှစ် ဆမ်းထားသော", "Sauce drizzle", "drizzled with sauce"),
			o("ingredients", "လတ်ဆတ်သော ချက်ပြုတ်စရာများ ဝန်းရံလျက်", "Ingredients around", "with fresh ingredients around it"),
			o("closeupfood", "ခံတွင်းတွေ့ဖွယ် အနီးကပ်ရိုက်ချက်", "Close-up", "in mouth-watering close-up"),
		),
		textNode("food_background", 726, false, c,
			"စားသောက်ဖွယ်ရာ နောက်ခံ?", "Background?",
			"on {value}",
			o("rustic", "သစ်သားစားပွဲဟောင်း", "Rustic table", "a rustic wooden table"),
			o("marble", "စကျင်ကျောက် ကောင်တာပေါ်", "Marble", "a marble countertop"),
			o("dark", "အမှောင်ရိပ် နောက်ခံ", "Dark moody", "a dark moody background"),
			o("bright", "လင်းလက်တောက်ပသော နောက်ခံ", "Bright & airy", "a bright, airy background"),
			o("market", "စည်ကားသော ဈေးမြင်ကွင်း နောက်ခံ", "Market", "a bustling market backdrop"),
		),
	}
}

// --- VEHICLE ---------------------------------------------------------------

func vehicleNodes() []Node {
	const c = "elements~=vehicle"
	return []Node{
		textNode("vehicle_what", 740, false, c,
			"မည်သည့် ယာဉ်အမျိုးအစားလဲ?", "What vehicle is it?",
			"{value}",
			o("car", "မော်တော်ကား", "Car", "a car"),
			o("sportscar", "စပေါ့ကား (Sports car)", "Sports car", "a sports car"),
			o("suv", "SUV ကားကြီး", "SUV", "an SUV"),
			o("vintage", "ရှေးဟောင်း ကား (Classic car)", "Vintage car", "a vintage car"),
			o("pickup", "ပစ်ကပ် ကား (Pickup truck)", "Pickup truck", "a pickup truck"),
			o("motorbike", "မော်တော်ဆိုင်ကယ်", "Motorcycle", "a motorcycle"),
			o("scooter", "စကူတာ (Scooter)", "Scooter", "a scooter"),
			o("bicycle", "စက်ဘီး", "Bicycle", "a bicycle"),
			o("trishaw", "မြန်မာ့ရိုးရာ ဆိုက်ကား", "Trishaw", "a traditional trishaw"),
			o("bus", "ဘတ်စ်ကား", "Bus", "a bus"),
			o("boat", "လှေ/သမ္ဗာန်", "Boat", "a boat"),
			o("jeep", "ဂျစ်ကား (Off-road Jeep)", "Jeep", "an off-road jeep"),
		),
		textNode("vehicle_color", 742, true, c,
			"ယာဉ်၏ အရောင်နှင့် အသွင်အပြင်?", "Color / finish?",
			"in {value}",
			o("glossyblack", "တလက်လက်တောက်ပသော အနက်ရောင်", "Glossy black", "glossy black"),
			o("pearlwhite", "ပုလဲဖြူရောင်", "Pearl white", "pearl white"),
			o("metalred", "မက်ထလစ် အနီရောင် (Metallic Red)", "Metallic red", "metallic red"),
			o("mattegrey", "မီးခိုးရောင်မှိုင်း (Matte Grey)", "Matte grey", "matte grey"),
			o("blue", "အပြာရင့်ရောင်", "Blue", "deep blue"),
			o("silver", "ငွေရောင် တောက်ပသော", "Silver", "silver"),
			o("yellow", "တောက်ပသော အဝါရောင်", "Yellow", "bright yellow"),
			o("chrome", "ခရိုမီယမ် ပြောင်လက်သော (Chrome)", "Chrome", "polished chrome"),
		),
		textNode("vehicle_setting", 744, false, c,
			"ယာဉ်ရှိနေသော နေရာ/ပတ်ဝန်းကျင်?", "Setting?",
			"{value}",
			o("mountain", "ကွေ့ကောက်သော တောင်ပေါ်လမ်း", "Mountain road", "on a winding mountain road"),
			o("city", "စည်ကားသော မြို့ပြလမ်းမ", "City street", "on a city street"),
			o("coast", "ပင်လယ် ကမ်းရိုးတန်းလမ်း", "Coastal highway", "on a coastal highway"),
			o("showroom", "ခေတ်မီ Showroom အရောင်းပြခန်း", "Showroom", "in a sleek showroom"),
			o("dirt", "ဖုန်ထူသော မြေသားလမ်းကြမ်း", "Dirt track", "on a dusty dirt track"),
			o("paddy", "စိမ်းလန်းသော စပါးခင်းဘေး", "By rice fields", "beside green rice fields"),
			o("rain", "မိုးရွာသွန်းနေသော လမ်းပေါ်", "In the rain", "in the rain"),
			o("night_city", "နီယွန်မီးရောင်စုံ မြို့ပြညမြင်ကွင်း", "Night city", "in a neon-lit night city"),
		),
		textNode("vehicle_angle", 746, true, c,
			"ကင်မရာ ရိုက်ကွက်ထောင့်?", "Angle?",
			"{value}",
			o("front34", "ရှေ့ဘက် သုံးပုံတစ်ပုံစောင်း (Front 3/4)", "Front 3/4", "a front three-quarter view"),
			o("side", "ဘေးတိုက် မြင်ကွင်း (Side Profile)", "Side profile", "a side-profile shot"),
			o("rear", "အနောက်ဘက် မြင်ကွင်း", "Rear", "a rear view"),
			o("low", "အောက်ခြေအနိမ့်မှ မော့ရိုက်ချက်", "Low angle", "a dramatic low angle"),
			o("action", "အရှိန်ဖြင့် မောင်းနှင်နေဟန် (Action Shot)", "Action shot", "a dynamic action shot"),
			o("aerial", "အပေါ်စီး ကောင်းကင်မြင်ကွင်း (Aerial View)", "Aerial", "an aerial view"),
		),
	}
}

// --- ARCHITECTURE / INTERIOR -----------------------------------------------

func architectureNodes() []Node {
	const c = "elements~=architecture"
	return []Node{
		textNode("arch_what", 760, false, c,
			"မည်သည့် အဆောက်အအုံ/အခန်း အမျိုးအစားလဲ?", "What structure is it?",
			"{value}",
			o("pagoda", "ရွှေရောင် စေတီပုထိုး", "Pagoda", "a golden pagoda"),
			o("monastery", "ကျွန်းသစ် ဘုန်းတော်ကြီးကျောင်း", "Monastery", "a teak monastery"),
			o("teakhouse", "ရှေးရိုးရာ ကျွန်းသစ်အိမ်", "Teak house", "a traditional teak house"),
			o("colonial", "ကိုလိုနီခေတ်လက်ရာ အဆောက်အအုံ", "Colonial building", "a colonial-era building"),
			o("stilt", "ရိုးရာ ဓနိ/ဝါးတဲအိမ်", "Stilt house", "a bamboo stilt house"),
			o("villa", "ခေတ်မီ ဗီလာတိုက်အိမ်", "Modern villa", "a modern villa"),
			o("skyscraper", "ခေတ်မီ မှန်စီ မိုးမျှော်တိုက်", "Skyscraper", "a glass skyscraper"),
			o("temple_int", "တန်ဆာဆင်ထားသော ဘုရားစေတီ အတွင်းခန်း", "Temple interior", "an ornate temple interior"),
			o("living", "နွေးထွေးလှပသော ဧည့်ခန်း", "Living room", "a cozy living room"),
			o("cafe", "စတိုင်ကျသော ကဖေးဆိုင် အတွင်းခန်း", "Cafe interior", "a stylish cafe interior"),
			o("lobby", "ခမ်းနားသော ဟိုတယ် ဧည့်ကြိုခန်းမ (Lobby)", "Hotel lobby", "a luxury hotel lobby"),
			o("bedroom", "အေးချမ်းတိတ်ဆိတ်သော အိပ်ခန်း", "Bedroom", "a serene bedroom"),
		),
		textNode("arch_style", 762, false, c,
			"ဗိသုကာ ဒီဇိုင်းစတိုင်?", "Design style?",
			"in a {value} style",
			o("burmese", "မြန်မာ့ရိုးရာ ဗိသုကာစတိုင်", "Traditional Burmese", "traditional Burmese"),
			o("colonial", "ကိုလိုနီခေတ် စတိုင်", "Colonial", "colonial"),
			o("minimalist", "ရိုးရှင်းသေသပ်သော စတိုင် (Minimalist)", "Minimalist", "modern minimalist"),
			o("contemporary", "ခေတ်ပြိုင် ဒီဇိုင်းစတိုင်", "Contemporary", "contemporary"),
			o("rustic", "ရိုးရိုးရှင်းရှင်း ကျေးလက်စတိုင်", "Rustic", "rustic"),
			o("luxury", "ခမ်းနားထည်ဝါသော ဇိမ်ခံစတိုင်", "Luxury", "luxurious"),
			o("scandi", "စကင်ဒီနေးဗီးယန်း စတိုင် (Scandinavian)", "Scandinavian", "Scandinavian"),
			o("industrial", "ခေတ်ဟောင်း စက်မှုဒီဇိုင်းစတိုင် (Industrial)", "Industrial", "industrial"),
			o("tropical", "အပူပိုင်းဒေသ သဘာဝစတိုင် (Tropical)", "Tropical", "tropical"),
		),
		textNode("arch_material", 764, true, c,
			"အဓိက အသုံးပြုထားသော ပစ္စည်း?", "Material?",
			"of {value}",
			o("teak", "ကျွန်းသစ်သား", "Teak wood", "teak wood"),
			o("brick", "အုတ်နီခဲ", "Brick", "brick"),
			o("concrete", "ကွန်ကရစ်", "Concrete", "concrete"),
			o("glasssteel", "မှန်နှင့် သံမဏိ", "Glass & steel", "glass and steel"),
			o("bamboo", "သဘာဝ ဝါး", "Bamboo", "bamboo"),
			o("marble", "စကျင်ကျောက်", "Marble", "marble"),
			o("gold", "ရွှေသင်္ကန်း / ရွှေချထားသော", "Gold-leaf", "gold-leaf"),
		),
		textNode("arch_setting", 766, false, c,
			"တည်ရှိရာ ပတ်ဝန်းကျင် အခင်းအကျင်း?", "Surroundings?",
			"{value}",
			o("garden", "စိမ်းလန်းသော ဥယျာဉ်ခြံ ဝန်းရံလျက်", "Gardens", "surrounded by lush gardens"),
			o("lake", "သာယာသော ရေကန်ဘေး", "By a lake", "by a calm lake"),
			o("city", "စည်ကားသော မြို့လယ်တွင်", "In the city", "in a busy city"),
			o("hilltop", "တောင်ကုန်းထိပ်ပေါ်တွင်", "On a hilltop", "on a hilltop"),
			o("forest", "သစ်တောအုပ်ကြီးအတွင်း", "In a forest", "nestled in a forest"),
			o("riverside", "မြစ်ကမ်းနဖူးတွင်", "Riverside", "on a riverside"),
		),
		textNode("arch_shot", 768, true, c,
			"ဗိသုကာ ရိုက်ကွက်ပုံစံ?", "Shot?",
			"{value}",
			o("exterior", "အဆောက်အအုံ အပြင်ဘက် မြင်ကွင်းကျယ်", "Wide exterior", "a wide exterior shot"),
			o("interior", "အတွင်းခန်း မြင်ကွင်းကျယ်", "Interior wide", "an interior wide-angle shot"),
			o("detail", "ဗိသုကာ လက်ရာ အသေးစိတ်", "Detail", "an architectural detail shot"),
			o("aerial", "အပေါ်စီး ကောင်းကင်မြင်ကွင်း (Aerial)", "Aerial", "an aerial view"),
			o("symmetry", "မျက်နှာစာ ညီညာမှု အချိုးကျ ရိုက်ချက်", "Symmetrical", "a symmetrical facade shot"),
		),
	}
}

// --- CHARACTER / FANTASY ---------------------------------------------------

func characterNodes() []Node {
	const c = "elements~=character"
	return []Node{
		textNode("char_type", 780, false, c,
			"မည်သည့် ဇာတ်ကောင် အမျိုးအစားလဲ?", "What character is it?",
			"{value}",
			o("warrior", "သတ္တိပြောင်မြောက်သော စစ်သည်တော်", "Warrior", "a fierce warrior"),
			o("king", "ပုဂံခေတ် မင်းဧကရာဇ်", "Ancient king", "a Bagan-era king"),
			o("wizard", "တန်ခိုးကြီး မှော်ဆရာ", "Wizard", "a powerful wizard"),
			o("nat", "မြန်မာ့ရိုးရာ နတ်နန်းစောင့်နတ်", "Nat spirit", "a Burmese nat spirit"),
			o("naga", "တန်ခိုးရှင် နဂါးမင်း", "Naga", "a mythical naga serpent"),
			o("goddess", "နတ်သမီး / နတ်မိမယ်", "Goddess", "a celestial goddess"),
			o("fairy", "ပန်းနတ်သမီးလေး (Fairy)", "Fairy", "a delicate fairy"),
			o("robot", "ခေတ်မီ စက်ရုပ်", "Robot", "a sleek robot"),
			o("cyberpunk", "Cyberpunk စတိုင် သူရဲကောင်း", "Cyberpunk hero", "a cyberpunk hacker"),
			o("superhero", "စူပါဟီးရိုး သူရဲကောင်း", "Superhero", "a superhero"),
			o("anime", "အန်နီမေး ဇာတ်ကောင်", "Anime hero", "an anime hero"),
			o("knight", "သံချပ်ကာဝတ် သူရဲကောင်း (Knight)", "Knight", "an armored knight"),
			o("ghost", "တစ္ဆေ / ဝိညာဉ်", "Ghost", "a ghostly spirit"),
			o("dragonrider", "နဂါးစီး သူရဲကောင်း", "Dragon rider", "a dragon rider"),
		),
		textNode("char_style", 782, false, c,
			"အနုပညာ ပုံဖော်မှု စတိုင်?", "Art style?",
			"in {value}",
			o("anime", "အန်နီမေး စတိုင် (Anime)", "Anime", "anime style"),
			o("pixar", "3D Pixar ကာတွန်းစတိုင်", "3D Pixar", "3D Pixar style"),
			o("darkfantasy", "Dark Fantasy စတိုင်", "Dark fantasy", "a dark fantasy style"),
			o("cyberpunk", "Cyberpunk စတိုင်", "Cyberpunk", "a cyberpunk style"),
			o("concept", "Concept Art စတိုင်", "Concept art", "detailed concept art"),
			o("realistic", "လက်တွေ့ဆန်သော ဖန်တစီစတိုင်", "Realistic fantasy", "a realistic fantasy style"),
			o("comic", "ကာတွန်းစာအုပ် စတိုင် (Comic book)", "Comic book", "a comic-book style"),
			o("chibi", "ချစ်စရာ Chibi ကာတွန်းစတိုင်", "Chibi", "a cute chibi style"),
		),
		textNode("char_outfit", 784, true, c,
			"ဇာတ်ကောင် ဝတ်ဆင်ထားသော ဝတ်စုံ?", "Outfit?",
			"wearing {value}",
			o("armor", "ခမ်းနားသော သံချပ်ကာ ဝတ်စုံ", "Armor", "ornate armor"),
			o("robe", "လွင့်မျောနေသော ဝတ်ရုံရှည်", "Robe", "a flowing robe"),
			o("royal", "မြန်မာ့ရှေးဟောင်း မင်းဝတ်ရတနာ စုံလင်စွာ", "Royal attire", "royal Burmese attire"),
			o("futuristic", "ခေတ်လွန် အနာဂတ်ဝတ်စုံ", "Futuristic suit", "a futuristic suit"),
			o("cloak", "စုတ်ပြဲဟောင်းနွမ်းနေသော ဝတ်ရုံရှည်", "Tattered cloak", "a tattered cloak"),
			o("magicaldress", "အလင်းလက်နေသော မှော်ဂါဝန်", "Magical dress", "a magical glowing dress"),
		),
		textNode("char_power", 786, true, c,
			"စွမ်းအားနှင့် လက်နက် ပစ္စည်း?", "Power / props?",
			"{value}",
			o("sword", "အလင်းလက်နေသော ဓား", "Glowing sword", "wielding a glowing sword"),
			o("magic", "မှော်အတတ် သုံးနေဟန်", "Casting magic", "casting magic"),
			o("fire", "မီးတောက်မီးလျှံများ ဝန်းရံလျက်", "With fire", "surrounded by fire"),
			o("wings", "တောက်ပသော အတောင်ပံများဖြင့်", "Glowing wings", "with glowing wings"),
			o("staff", "မှော်တောင်ဝှေး ကိုင်ဆောင်ထားသော", "Staff", "holding a magical staff"),
			o("lightning", "လျှပ်စီးလက်နေသော စွမ်းအားဖြင့်", "Lightning", "crackling with lightning"),
			o("bow", "လေးမြှား ချိန်ရွယ်နေဟန်", "Bow", "drawing a bow"),
		),
		textNode("char_setting", 788, false, c,
			"ဇာတ်ကောင် ရှိနေသော နောက်ခံကမ္ဘာ?", "Setting?",
			"{value}",
			o("forest", "မှော်ဝင် သစ်တောနက်", "Enchanted forest", "in an enchanted forest"),
			o("neoncity", "နီယွန်ရောင်စုံ မြို့ပြကြီး", "Neon city", "in a neon city"),
			o("battlefield", "ပြင်းထန်သော စစ်မြေပြင်", "Battlefield", "on a battlefield"),
			o("temple", "လျှို့ဝှက်ဆန်းကြယ် ရှေးဟောင်း ဘုရားကျောင်း", "Mystical temple", "in a mystical temple"),
			o("clouds", "တိမ်တိုက်များ အလယ်တွင်", "Among clouds", "among the clouds"),
			o("bagan", "ရှေးခေတ် ပုဂံပြည် မြင်ကွင်း", "Ancient Bagan", "in ancient Bagan"),
			o("ruins", "ရှေးဟောင်း အပျက်အစီးများကြား", "Ruins", "among ancient ruins"),
		),
	}
}

// --- LOGO / TYPOGRAPHY -----------------------------------------------------

func logoNodes() []Node {
	const c = "elements~=logo"
	return []Node{
		textNode("logo_text", 800, false, c,
			"မည်သည့် စာသား/အမှတ်တံဆိပ် အမည်လဲ?", "What text / name?",
			"the text \"{value}\"",
			o("show", "SHOW", "SHOW", "SHOW"),
			o("cafe", "Café", "Café", "Café"),
			o("myanmar", "မြန်မာ", "မြန်မာ", "မြန်မာ"),
			o("brand", "Brand", "Brand", "Brand"),
			o("shop", "Shop", "Shop", "Shop"),
		),
		textNode("logo_style", 802, false, c,
			"လိုဂို (Logo) ဒီဇိုင်းစတိုင်?", "Logo style?",
			"as {value}",
			o("minimal", "ရိုးရှင်းသေသပ်သော စတိုင် (Minimalist)", "Minimalist", "a minimalist logo"),
			o("vintage", "ခေတ်ဟောင်း တံဆိပ်စတိုင် (Vintage badge)", "Vintage badge", "a vintage badge logo"),
			o("wordmark", "ခေတ်မီ စာသားသီးသန့် (Wordmark)", "Modern wordmark", "a modern wordmark"),
			o("script", "လက်ရေးစောင်း စတိုင် (Script)", "Hand-lettered", "a hand-lettered script logo"),
			o("bold", "စာလုံးထူ စတိုင် (Bold Sans)", "Bold sans", "a bold sans-serif logo"),
			o("luxury", "ရွှေရောင် ခမ်းနားသော အမှတ်တံဆိပ် (Luxury Emblem)", "Luxury emblem", "a luxury gold emblem"),
			o("playful", "ချစ်စရာ ကာတွန်းစတိုင် (Playful)", "Playful", "a playful cartoon logo"),
			o("tech", "ခေတ်မီ နည်းပညာစတိုင် (Tech)", "Tech", "a modern tech logo"),
			o("monogram", "အက္ခရာပေါင်း အမှတ်တံဆိပ် (Monogram)", "Monogram", "an elegant monogram"),
			o("esports", "အားကစား/ဂိမ်း အသင်းတံဆိပ် (Esports)", "Esports", "a bold esports logo"),
		),
		textNode("logo_color", 804, true, c,
			"လိုဂို အရောင်ရွေးချယ်မှု?", "Color?",
			"in {value}",
			o("bw", "အဖြူအမည်း (Black & White)", "Black & white", "black and white"),
			o("goldblack", "အနက်ပေါ်တွင် ရွှေရောင်", "Gold on black", "gold on black"),
			o("pastel", "နုညံ့သော အရောင်များ (Pastel)", "Pastel", "soft pastels"),
			o("vibrant", "တောက်ပစိုပြည်သော အရောင်များ", "Vibrant", "vibrant colors"),
			o("mono", "အရောင်တစ်မျိုးတည်း (Monochrome)", "Monochrome", "monochrome"),
			o("neon", "နီယွန်ရောင်စုံ (Neon)", "Neon", "neon colors"),
		),
		textNode("logo_element", 806, true, c,
			"ပါဝင်စေလိုသော သင်္ကေတ / Icon?", "Symbol / icon?",
			"{value}",
			o("leaf", "သစ်ရွက် သင်္ကေတ", "Leaf", "with a leaf icon"),
			o("mountain", "တောင်တန်း သင်္ကေတ", "Mountain", "with a mountain symbol"),
			o("coffee", "ကော်ဖီခွက် သင်္ကေတ", "Coffee cup", "with a coffee-cup icon"),
			o("lion", "ခြင်္သေ့ သင်္ကေတ", "Lion", "with a lion emblem"),
			o("bird", "ငှက် သင်္ကေတ", "Bird", "with a bird mark"),
			o("abstract", "စိတ်ကူးပုံဖော် သင်္ကေတ (Abstract)", "Abstract mark", "with an abstract mark"),
			o("textonly", "စာသား သီးသန့် (Icon မပါ)", "Text only", "text only, no icon"),
		),
		textNode("logo_mockup", 808, false, c,
			"လိုဂိုကို မည်သည့်နေရာတွင် ဖော်ပြပြသမလဲ?", "Shown on?",
			"on {value}",
			o("clean", "ရိုးရှင်းသန့်ရှင်းသော နောက်ခံ", "Clean background", "a clean background"),
			o("card", "လိပ်စာကတ်ပေါ်တွင် (Business Card)", "Business card", "a business card mockup"),
			o("sign", "ဆိုင် ဆိုင်းဘုတ်ပေါ်တွင်", "Signboard", "a shop signboard"),
			o("tshirt", "တီရှပ်အင်္ကျီပေါ်တွင်", "T-shirt", "a t-shirt mockup"),
			o("packaging", "ထုတ်ကုန် ထုပ်ပိုးမှုပေါ်တွင်", "Packaging", "product packaging"),
		),
	}
}
